services:
  app:
    image: ${IMAGE_REF} ##The image URL should be replaced with your own
    working_dir: /var/www
    env_file: runtime.prod.env #The image knows to look for a specific key
    ports:
      - "127.0.0.1:8081:80"
    depends_on: [db, redis]
    volumes:
      - storage-data:/var/www/storage
    restart: unless-stopped

  db:
    image: mysql:8.0
    env_file: runtime.prod.env # <-- use env_file, not ${...} substitution
    volumes:
      - db-data:/var/lib/mysql
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    restart: unless-stopped

  scheduler:
    image: ${IMAGE_REF}
    working_dir: /var/www
    env_file: runtime.prod.env
    depends_on: [app, db, redis]
    command: php artisan schedule:work
    volumes:
      - storage-data:/var/www/storage
    restart: unless-stopped

  queue:
    image: ${IMAGE_REF}
    working_dir: /var/www
    env_file: runtime.prod.env
    depends_on: [app, db, redis]
    command: php artisan queue:work --sleep=1 --tries=3
    volumes:
      - storage-data:/var/www/storage # â† mount storage for failed_jobs.log
    restart: unless-stopped

volumes:
  db-data:
  storage-data:
